# Builds the project
name: Android Feature Branch CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build, Sign & Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: set up JDK 17
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Stop Gradle daemons
        run: ./gradlew --stop

      - name: Decode keystore
        id: write_base64_file
        shell: bash
        run: |
          echo "${{ secrets.SIGNINGKEY_BASE64 }}" > mLauncher.jks.tmp
          base64 -d -i mLauncher.jks.tmp > mLauncher.jks
          rm mLauncher.jks.tmp

          mkdir -p app
          mv mLauncher.jks app/

          DESTINATION_FILE="app/mLauncher.jks"
          echo "filePath=$DESTINATION_FILE" >> "$GITHUB_OUTPUT"
          echo "Keystore written to $DESTINATION_FILE"

      - name: Build with Gradle
        run: ./gradlew clean assembleProdRelease --refresh-dependencies --no-daemon
        env:
          JAVA_TOOL_OPTIONS: "-Dhttps.protocols=TLSv1.2"
          KEY_STORE_FILE: ${{ steps.write_base64_file.outputs.filePath }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mLauncher-${{ github.ref_name }}-signed
          path: app/build/outputs/apk/prod/release/*.apk
          retention-days: 7

      - name: Secure keystore cleanup
        if: always()
        shell: bash
        run: |
          shred -u app/mLauncher.jks || rm -f app/mLauncher.jks
